### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by Rosewulf22** [Azagwen/Rainbow_kittens_theme#4]
It says "META not found" help...?

**Comment by Azagwen** [comment]
Sorry for the replying time, I usually never go on github other then when I update the theme.
I've never seen this issue :/
I've seen people saying the theme broke because of discord' updates, this could be related to the theme's first line which is the META (version,; authors, description...) but THERE IS a META line in the theme so I don't know, sorry :/

Try the newer version of the theme and see If it works.
